model_list:
  - model_name: "*"
    litellm_params:
      model: anthropic/*
      api_key: 9f8YXkdAKwulsWeKRLtGF2aY5jvfz0IhqFs07F9s2V3b1qd0LAeEJQQJ99BDACHYHv6XJ3w3AAAAACOGU68s
      api_base: https://ayesh-m9o7pip4-eastus2.openai.azure.com/anthropic/
  # - model_name: qwen-vl
  #   litellm_params:
  #     model: Qwen/Qwen3-VL-8B-Instruct
  #     api_key: NA
  #     api_base: http://host.docker.internal:8003/v1
  - model_name: qwen
    litellm_params:
      model: qwen/qwen3.6-27b
      custom_llm_provider: openai
      api_key: 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
      api_base: https://api.groq.com/openai/v1
      additional_drop_params: ['reasoning_effort', 'reasoning.effort']

litellm_settings:
  drop_params: true
      

general_settings:
  master_key: "sk-dQr753J884Tt-ZmTjQGMYVCrAFA-NLMWj-cwxFPtfbI"
  database_url: "postgresql://llmproxy:dbpassword9090@db:5432/litellm"
  drop_params: true
  allowed_fails: 0
  num_retries: 0

environment_variables:
  OPENAI_API_KEY: "9f8YXkdAKwulsWeKRLtGF2aY5jvfz0IhqFs07F9s2V3b1qd0LAeEJQQJ99BDACHYHv6XJ3w3AAAAACOGU68s"
  LITELLM_MASTER_KEY: "admin123"
  UI_USERNAME: "admin"
  UI_PASSWORD: "admin123"